# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[files]
extend-exclude = [
  # The test data have typos, or at least uncommon spelling. We do not care
  # about them as they are not customer visible.
  "generator/**/testdata/**",
  "testdata/**",
]

[type.mustache]
extend-glob = ["*.mustache"]

[type.mustache.extend-words]
ser = "ser"

[default.extend-words]
# This is correct, https://en.wikipedia.org/wiki/Comune
comune = "comune"
# A common spelling, but typos-cli prefers implementers
implementors = "implementors"
# from google/api:
advices    = "advices"    # In the code, too late to fix.
readablity = "readablity"
# src/generated/api/servicemanagement/v1 has a typo, it needs to be fixed
# upstream.
unspecifed = "unspecifed"
# src/generated/appengine/v1 has a typo, it needs to be fixed upstream.
explictly = "explictly"
# src/generated/cloud/accessapproval/v1, these are intentional and expected
# to remain as spelled forever.
OCE = "OCE"
NAM = "NAM"
# src/generated/bigtable/admin/v2, this may be a typo or not, but in any case,
# it cannot be changed: it is the name of an IAM role.
encrypter = "encrypter"
# src/generated/container/v1 has some typos, they need to be fixed upstream.
accessbile    = "accessbile"
attahced      = "attahced"
documnetation = "documnetation"
specififed    = "specififed"
wilcards      = "wilcards"
# src/generated/cloud/aiplatform/v1 has some typos, they need to be fixed
# upstream.
assiociated = "assiociated"
creatation  = "creatation"
geneated    = "geneated"
inifinity   = "inifinity"
mathching   = "mathching"
overrided   = "overrided"
predifined  = "predifined"
simpy       = "simpy"
specifing   = "specifing"
# src/generated/cloud/alloydb/connectors/v1, has a typo, it needs to be fixed
# upstream.
authentiation = "authentiation"
# src/generated/cloud/alloydb/v1, has some typos, they need to be fixed upstream.
ephemereal   = "ephemereal"
ceritificate = "ceritificate"
instaces     = "instaces"
# src/generated/cloud/config/v1 has a typo, it needs to be fixed upstream.
identifiy = "identifiy"
# src/generated/cloud/dataproc/v1, has some typos, they need to be fixed upstream.
andd = "andd"
# src/generated/cloud/baremetalsolution/v2 has typos, they need to be fixed
# upstream.
idenfity   = "idenfity"
provisiong = "provisiong"
# src/generated/cloud/bigquerydatatransfer/v1 has typos, they need to be fixed
# upstream.
desination = "desination"
# src/generated/cloud/clouddms/v1 has typos, they need to be fixed upstream.
availablility = "availablility"
decendents    = "decendents"
# src/generated/cloud/connectors/v1 has typos, they need to be fixed upstream.
prinicpal = "prinicpal"
vaiable   = "vaiable"
# src/generated/cloud/contactcenterinsights/v1 has typos, they need to be fixed
# upstream.
telphony = "telphony"
analyis  = "analyis"
abolute  = "abolute"
# src/generated/dataplex/v1 has typos, they need to be fixed upstream
autorization = "autorization"
delele       = "delele"
createed     = "createed"
# src/generated/cloud/dialogflow/cx/v3 has typos, they need to be fixed
# upstream.
verion = "verion"
# src/generated/cloud/discoveryengine/v1 has a borderline word.
inputed = "inputed"
# src/generated/cloud/eventarc/v1 has a typo, it needs to be fixed upstream.
enpdoint = "enpdoint"
oder     = "oder"
# src/generated/cloud/gkebackup/v1 has a typo, it needs to be fixed upstream.
everyting = "everyting"
# src/generated/cloud/gkemulticloud/v1 has a typo, it needs to be fixed
# upstream.
speficied = "speficied"
# src/generated/cloud/managedidentities/v1 has typos, they need to be fixed
# upstream.
segement  = "segement"
identites = "identites"
# src/generated/cloud/migrationcenter/v1 has typos, they need to be fixed
# upstream.
pount    = "pount"
staticly = "staticly"
# src/generated/modelarmor/v1 has a typo, it needs to be fixed upstream.
Insepction = "Insepction"
# src/generated/cloud/networkconnectivity has a typo, it needs to be fixed
# upstream.
flexibile = "flexibile"
throuh    = "throuh"
# src/generated/cloud/networkservices/v1 has a typo, it needs to be fixed
# upstream.
forwareded = "forwareded"
# src/generated/cloud/notebooks/v2 has a typo, it needs to be fixed upstream.
maxmium = "maxmium"
# src/generated/cloud/optimization/v1 has a false positive. Both "preemptible"
# and "preemptable" are common spellings, but `typos` only accepts the former.
preemptable = "preemptable"
# src/generated/cloud/orgpolicy/v1 has typos, they need to be fixed upstream.
settting   = "settting"
supercedes = "supercedes"
# src/generated/cloud/parametermanager/v1 has a typo, it needs to be fixed
# upstream.
substituion = "substituion"
# src/generated/cloud/redis/cluster/v1 has some typos, they need to be fixed
# upstream.
enpoints   = "enpoints"
maitenance = "maitenance"
# src/generated/cloud/retail/v2 has some typos, they need to be fixed upstream.
wil    = "wil"
goig   = "goig"
sesion = "sesion"
overal = "overal"
# Newly caught
specifictions = "specifictions"
# src/generated/cloud/run/v2 has some typos, they need to be fixed upstream.
permamently = "permamently"
# src/generated/cloud/securesourcemanager/v1 has some typos, they need to be
# fixed upstream.
desginated = "desginated"
# src/generated/cloud/security/privateca/v1 has a typo, it needs to be fixed
# upstream.
relavent = "relavent"
# src/generated/cloud/speech/v2 has a typo, needs to be fixed upstream.
representes = "representes"
# src/generated/cloud/sql/v1 has a typo, needs to be fixed upstream.
corresponsing = "corresponsing"
# src/generated/cloud/talent/v4 gives an example of a typo. This is correct.
enginee = "enginee"
# src/generated/cloud/telcoautomation/v1 has a typo, it needs to be fixed
# upstream.
initate = "initate"
# src/generated/cloud/timeseriesinsights/v1 has a typo, it is fixed at the
# source, but it has not propagated yet.
anormaly = "anormaly"
# src/generated/cloud/videointelligence/v1 has typos, they need to be fixed upstream.
coordindate  = "coordindate"
trignometric = "trignometric"
# src/generated/cloud/vision/v1 has a false positive.
pn = "pn"
# src/generated/cloud/vmmigration/v1 has typos, they need to be fixed upstream.
clonning    = "clonning"
informatiom = "informatiom"
# src/generated/cloud/workstations/v1 has a typo, it needs to be fixed upstream.
attachemnt = "attachemnt"
# src/generated/datastore/admin/v1 has a typo, needs to be fixed upstream.
Ths = "Ths"
# src/generated/devtools/cloudbuild/v2 has a typo, needs to be fixed upstream.
maching = "maching"
# src/generated/grafeas has (maybe) typos. These are not fixable:
intoto = "intoto" # should be "in_toto" :shrug:
# src/generated/privacy/dlp/v2 has a typo, needs to be fixed upstream.
similiarly = "similiarly"
# src/generated/spanner/admin/database/v1 has a typo, needs to be fixed upstream.
intital = "intital"
# src/generated/rpc/types has a typo, needs to be fixed upstream.
orginates = "orginates"
# src/generated/type say "Requestor", `typos` recommends `Requester`.
requestor = "requestor"
# src/generated/storagetransfer has typos, they need to be fixed upstream.
ovewritten   = "ovewritten"
combintation = "combintation"

# These are not good ideas for "extend-words" because they will catch too many
# true positives
[default]
extend-ignore-re = [
  # This is intentional, we call the factory function `ser()` to avoid the
  # `serde()` which is ambiguous:
  "Error::ser",
  # This is intentional, `typ` is the name of a field in OAuth2 claims:
  "\"typ\"",
  "\\Wtyp:",
  "test_typ\"",
  # src/generated/api/cloudquotas/v1 has types that are better handled in a RE:
  "DimenisonInfo",
  # src/generated/cloud/aiplatform has a typo in the code. Won't be fixed.
  # Seems too risky to ignore the word, a RE seems cleaner
  "CheckTrialEarlyStoppingStateMetatdata",
  "FIELDs",
  # src/generated/cloud/backupdr/v1 uses `BA` in fields and enums.
  "WITHIN_ORG_BUT_UNRESTRICTED_FOR_BA",
  "WithinOrgButUnrestrictedForBa",
  "ba_proxy_uri",
  "to BA proxy",
  # src/generated/cloud/bigquery/migration/v2 uses product names that look like
  # typos. They should stay as they are.
  "Tha task is paused", # accepting "Tha" seems too broad
  "Vertica2BQ",
  "VerticaDialect",
  "\\W[Vv]ertica\\W",
  "vertica_dialect",
  # src/generated/cloud/bigquery/v2 uses `ALS` which is a false positive typo
  # for `ALSO`
  "weighted-ALS",
  "weighted-als",
  # src/generated/cloud/config/v1 has false positives on a product name.
  "HashiCorp",
  # src/generated/cloud/dialogflow/v2 has some typos, ignoring "whe" everywhere
  # seems too broad.
  " whe ",
  # src/generated/cloud/dataplex/v1 has a typo in a field name. Cannot be fixed.
  "evalution_type",
  # src/generated/cloud/dialogflow/v2 uses enums that look like typos.
  "GOST R 34",
  "GOST3411",
  "Gost3411",
  # src/generated/cloud/firestore has a typo, needs to be fixed upstream.
  "`TargetChage\\.",
  # src/generated/cloud/gkemulticloud/v1 uses AKS as an acronym.
  "\\WAKS\\W",
  "\\Waks\\W",
  # src/generated/cloud/licensemanager/v1 uses `MAK` as an acronym.
  "(MAK)",
  # src/generated/cloud/orchestration/airflow/service/v1, typos splits this as
  # "I-Dentifier"
  "IDentifier",
  "openpgp4fpr", # ignoring `fpr` seems ill-advised
  # src/generated/cloud/osconfig/v1, arguably not a typo.
  "ANDed", # ignoring `Ded` see
  # src/generated/cloud/retail/v2, apparently this is correct in some cases.
  "mis-match",
  # src/generated/cloud/securesourcemanager uses `unicode-tou`, ignoring `tou`
  # seems too risky.
  "unicode-tou",
  # src/generated/cloud/securesourcemanager uses `cc-by-nd-*`, ignoring `nd`
  # seems too risky.
  "cc-by-nc-nd-[0-9]",
  "cc-by-nd-[0-9]",
  "infor-cms",         # Product name
  "synopsys-vcs",      # Product name
  # src/generated/cloud/video/stitcher/v1 use "GAM" as an acronym.
  "Gam[A-Z]",
  "\\WGAM\\W",
  "gam_[a-z]",
]
