# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[files]
extend-exclude = [
  # The test data have typos, or at least uncommon spelling. We do not care
  # about them as they are not customer visible.
  "testdata/**",
  "tools/cmd/docfx/testdata/**",
  # Generated libraries often contain typos coming from upstream protos.
  "/go.work.sum",
  "src/*/src/generated/**",
  "src/generated/**",
  # This file contains fixes for typos and therefore has the original typo in it.
  "librarian.yaml",
]

[type.mustache]
extend-glob = ["*.mustache"]

[type.mustache.extend-words]
ser = "ser"

# These are not good ideas for "extend-words" because they will catch too many
# true positives
[default]
extend-ignore-re = [
  # This is intentional, we call the factory function `ser()` to avoid the
  # `serde()` which is ambiguous:
  "Error::ser",
  # This is intentional, `typ` is the name of a field in OAuth2 claims:
  "\"typ\"",
  "\\Wtyp:",
  "test_typ\"",
  # The name of a Cloud Storage dual region, used in some tests.
  "NAM4",
]
