# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[general]
specification-source = 'google/spanner/admin/database/v1'
service-config = 'google/spanner/admin/database/v1/spanner.yaml'

[codec]
version        = '1.3.0'
copyright-year       = '2025'

[source]
skipped-ids = """\
.google.spanner.admin.database.v1.DatabaseAdmin.InternalUpdateGraphOperation,\
.google.spanner.admin.database.v1.InternalUpdateGraphOperationRequest,\
.google.spanner.admin.database.v1.InternalUpdateGraphOperationResponse\
"""

[[documentation-overrides]]
id      = '.google.spanner.admin.database.v1.ListBackupsRequest.filter'
match   = """
  * `database:prod`
         - The database's name contains the string "prod".
  * `state:CREATING` - The backup is pending creation.
  * `state:READY` - The backup is fully created and ready for use.
  * `(name:howl) AND (create_time < \\"2018-03-28T14:50:00Z\\")`
         - The backup name contains the string "howl" and `create_time`
             of the backup is before 2018-03-28T14:50:00Z.
  * `expire_time < \\"2018-03-28T14:50:00Z\\"`
         - The backup `expire_time` is before 2018-03-28T14:50:00Z.
  * `size_bytes > 10000000000` - The backup's size is greater than 10GB
  * `backup_schedules:daily`
         - The backup is created from a schedule with "daily" in its name."""
replace = """
  * `database:prod` - The database's name contains the string "prod".
  * `state:CREATING` - The backup is pending creation.
  * `state:READY` - The backup is fully created and ready for use.
  * `(name:howl) AND (create_time < \\"2018-03-28T14:50:00Z\\")` - The backup
    name contains the string "howl" and `create_time` of the backup is before
    2018-03-28T14:50:00Z.
  * `expire_time < \\"2018-03-28T14:50:00Z\\"` - The backup `expire_time` is
    before 2018-03-28T14:50:00Z.
  * `size_bytes > 10000000000` - The backup's size is greater than 10GB
  * `backup_schedules:daily` - The backup is created from a schedule with
    "daily" in its name."""
