# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[package]
name              = "grpc-server"
description       = "A server used in the gax integration tests."
version           = "0.0.0"
build             = "build.rs"
edition.workspace = true
publish           = false

[features]
_generate-protos = ["dep:tonic-build"]

[dependencies]
anyhow.workspace = true
axum.workspace   = true
http             = "1"
prost            = { workspace = true, default-features = true }
serde_json       = "1"
tokio            = { version = "1", features = ["macros"] }
tokio-stream     = "0.1"
tonic            = { workspace = true, default-features = true }
# Local dependencies
auth = { path = "../../auth", package = "google-cloud-auth" }
gax  = { path = "../../gax", package = "google-cloud-gax" }
gaxi = { path = "../../gax-internal", package = "google-cloud-gax-internal", features = ["_internal_grpc_client"] }

[build-dependencies]
tonic-build = { workspace = true, optional = true }
