# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[general]
language             = 'rust'
specification-source = 'google/storage/v2'
service-config       = 'google/storage/v2/storage_v2.yaml'

[source]
included-ids = """\
    .google.storage.v2.Storage.DeleteBucket,\
    .google.storage.v2.Storage.GetBucket,\
    .google.storage.v2.Storage.CreateBucket,\
    .google.storage.v2.Storage.ListBuckets,\
    .google.storage.v2.Storage.LockBucketRetentionPolicy,\
    .google.storage.v2.Storage.GetIamPolicy,\
    .google.storage.v2.Storage.SetIamPolicy,\
    .google.storage.v2.Storage.TestIamPermissions,\
    .google.storage.v2.Storage.UpdateBucket,\
    .google.storage.v2.Storage.ComposeObject,\
    .google.storage.v2.Storage.DeleteObject,\
    .google.storage.v2.Storage.RestoreObject,\
    .google.storage.v2.Storage.GetObject,\
    .google.storage.v2.Storage.UpdateObject,\
    .google.storage.v2.Storage.ListObjects,\
    .google.storage.v2.Storage.RewriteObject,\
    .google.storage.v2.Storage.MoveObject,\
    .google.storage.v2.ReadObjectRequest,\
    .google.storage.v2.WriteObjectSpec\
    """

[codec]
copyright-year            = '2025'
template-override         = 'templates/grpc-client'
package-name-override     = 'google-cloud-storage'
name-overrides            = '.google.storage.v2.Storage=StorageControl'
include-grpc-only-methods = 'true'
has-veneer                = 'true'
