name: Lint

on:
  push:
  pull_request:
    types: [opened, reopened]

jobs:
  spell:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - run: |
        rustup component list
        cargo install typos-cli --version 1.26.8
    - run:
        typos
